# AI Commit Message Generator Configuration
# Store this file in ~/.config/ai-commit-msg/config.toml (or $XDG_CONFIG_HOME/ai-commit-msg/config.toml)

# Verbosity level: 0=Silent, 1=Normal, 2=Verbose, 3=MoreVerbose, 4=Debug
verbosity = 2

# Number of context lines for git diff (default: 3)
# Use -1 for maximum context (entire file)
context_lines = 10

# Claude model to use
model_name = "claude-3-haiku-20240307"

# Whether to remember command-line options for future use
remember_flags = true
